// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXWPD9X6OMcav3rFlWhaC2WAV1BmI0HQ',
    appId: '1:60518073247:android:45164168095fe741e9f3aa',
    messagingSenderId: '60518073247',
    projectId: 'new-jeeey',
    storageBucket: 'new-jeeey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeeP1auJewTZy1d0JdPNMqPh6KZXsSkl0',
    appId: '1:60518073247:ios:50ee926288968383e9f3aa',
    messagingSenderId: '60518073247',
    projectId: 'new-jeeey',
    storageBucket: 'new-jeeey.firebasestorage.app',
    androidClientId: '60518073247-81o6rhjs1l9s3tot5s6j14sari241lk2.apps.googleusercontent.com',
    iosClientId: '60518073247-ochj1igem7rbg077jl5g2f70i7ghajfe.apps.googleusercontent.com',
    iosBundleId: 'com.devstation.jeeey',
  );
}
